export const CHANNEL_REGISTRY_SERVICE = Symbol('CHANNEL_REGISTRY_SERVICE');
export const CHANNEL_PACKAGE_SERVICE = Symbol('CHANNEL_PACKAGE_SERVICE');
export const PUBLICATION_ELIGIBILITY_SERVICE = Symbol('PUBLICATION_ELIGIBILITY_SERVICE');
export const PUBLICATION_COMMAND_SERVICE = Symbol('PUBLICATION_COMMAND_SERVICE');
export const PUBLICATION_QUERY_SERVICE = Symbol('PUBLICATION_QUERY_SERVICE');
export const PUBLICATION_REMOTE_STATUS_REFRESH_SERVICE = Symbol(
  'PUBLICATION_REMOTE_STATUS_REFRESH_SERVICE',
);
export const CHANNEL_AUTHORIZATION_SERVICE = Symbol('CHANNEL_AUTHORIZATION_SERVICE');
export const SIGNED_WEBHOOK_ENDPOINT_VERIFICATION_SERVICE = Symbol(
  'SIGNED_WEBHOOK_ENDPOINT_VERIFICATION_SERVICE',
);
