export const PRIVACY_AUDIT_SERVICE = Symbol('PRIVACY_AUDIT_SERVICE');
export const PRIVACY_AUDIT_STORE = Symbol('PRIVACY_AUDIT_STORE');
export const PRIVACY_TENANCY_STORE = Symbol('PRIVACY_TENANCY_STORE');
export const DELETION_RECEIPT_TOKEN_SERVICE = Symbol('DELETION_RECEIPT_TOKEN_SERVICE');
